QT += gui
QT += xml

CONFIG += c++11 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

QMAKE_CXXFLAGS += -msse2

SOURCES += main.cpp \
    libigl/include/igl/copyleft/marching_cubes.cpp \
    libigl/include/igl/AABB.cpp \
    libigl/include/igl/accumarray.cpp \
    libigl/include/igl/active_set.cpp \
    libigl/include/igl/adjacency_list.cpp \
    libigl/include/igl/adjacency_matrix.cpp \
    libigl/include/igl/all_edges.cpp \
    libigl/include/igl/all_pairs_distances.cpp \
    libigl/include/igl/all.cpp \
    libigl/include/igl/ambient_occlusion.cpp \
    libigl/include/igl/angular_distance.cpp \
    libigl/include/igl/any_of.cpp \
    libigl/include/igl/any.cpp \
    libigl/include/igl/arap_dof.cpp \
    libigl/include/igl/arap_linear_block.cpp \
    libigl/include/igl/arap_rhs.cpp \
    libigl/include/igl/arap.cpp \
    libigl/include/igl/AtA_cached.cpp \
    libigl/include/igl/average_onto_faces.cpp \
    libigl/include/igl/average_onto_vertices.cpp \
    libigl/include/igl/avg_edge_length.cpp \
    libigl/include/igl/axis_angle_to_quat.cpp \
    libigl/include/igl/barycenter.cpp \
    libigl/include/igl/barycentric_coordinates.cpp \
    libigl/include/igl/barycentric_to_global.cpp \
    libigl/include/igl/basename.cpp \
    libigl/include/igl/bbw.cpp \
    libigl/include/igl/bfs_orient.cpp \
    libigl/include/igl/bfs.cpp \
    libigl/include/igl/biharmonic_coordinates.cpp \
    libigl/include/igl/bijective_composite_harmonic_mapping.cpp \
    libigl/include/igl/bone_parents.cpp \
    libigl/include/igl/boundary_conditions.cpp \
    libigl/include/igl/boundary_facets.cpp \
    libigl/include/igl/boundary_loop.cpp \
    libigl/include/igl/bounding_box_diagonal.cpp \
    libigl/include/igl/bounding_box.cpp \
    libigl/include/igl/canonical_quaternions.cpp \
    libigl/include/igl/cat.cpp \
    libigl/include/igl/ceil.cpp \
    libigl/include/igl/centroid.cpp \
    libigl/include/igl/circulation.cpp \
    libigl/include/igl/circumradius.cpp \
    libigl/include/igl/collapse_edge.cpp \
    libigl/include/igl/collapse_small_triangles.cpp \
    libigl/include/igl/colon.cpp \
    libigl/include/igl/colormap.cpp \
    libigl/include/igl/column_to_quats.cpp \
    libigl/include/igl/columnize.cpp \
    libigl/include/igl/comb_cross_field.cpp \
    libigl/include/igl/comb_frame_field.cpp \
    libigl/include/igl/comb_line_field.cpp \
    libigl/include/igl/combine.cpp \
    libigl/include/igl/compute_frame_field_bisectors.cpp \
    libigl/include/igl/connect_boundary_to_infinity.cpp \
    libigl/include/igl/cotmatrix_entries.cpp \
    libigl/include/igl/cotmatrix_intrinsic.cpp \
    libigl/include/igl/cotmatrix.cpp \
    libigl/include/igl/count.cpp \
    libigl/include/igl/covariance_scatter_matrix.cpp \
    libigl/include/igl/cross_field_mismatch.cpp \
    libigl/include/igl/cross.cpp \
    libigl/include/igl/crouzeix_raviart_cotmatrix.cpp \
    libigl/include/igl/crouzeix_raviart_massmatrix.cpp \
    libigl/include/igl/cumprod.cpp \
    libigl/include/igl/cumsum.cpp \
    libigl/include/igl/cut_mesh_from_singularities.cpp \
    libigl/include/igl/cut_mesh.cpp \
    libigl/include/igl/cut_to_disk.cpp \
    libigl/include/igl/cylinder.cpp \
    libigl/include/igl/dated_copy.cpp \
    libigl/include/igl/decimate.cpp \
    libigl/include/igl/deform_skeleton.cpp \
    libigl/include/igl/delaunay_triangulation.cpp \
    libigl/include/igl/dfs.cpp \
    libigl/include/igl/diag.cpp \
    libigl/include/igl/dihedral_angles.cpp \
    libigl/include/igl/dijkstra.cpp \
    libigl/include/igl/directed_edge_orientations.cpp \
    libigl/include/igl/directed_edge_parents.cpp \
    libigl/include/igl/dirname.cpp \
    libigl/include/igl/dot_row.cpp \
    libigl/include/igl/dot.cpp \
    libigl/include/igl/doublearea.cpp \
    libigl/include/igl/dqs.cpp \
    libigl/include/igl/ears.cpp \
    libigl/include/igl/edge_collapse_is_valid.cpp \
    libigl/include/igl/edge_exists_near.cpp \
    libigl/include/igl/edge_flaps.cpp \
    libigl/include/igl/edge_lengths.cpp \
    libigl/include/igl/edge_topology.cpp \
    libigl/include/igl/edges_to_path.cpp \
    libigl/include/igl/edges.cpp \
    libigl/include/igl/eigs.cpp \
    libigl/include/igl/EPS.cpp \
    libigl/include/igl/euler_characteristic.cpp \
    libigl/include/igl/exact_geodesic.cpp \
    libigl/include/igl/example_fun.cpp \
    libigl/include/igl/exterior_edges.cpp \
    libigl/include/igl/extract_manifold_patches.cpp \
    libigl/include/igl/extract_non_manifold_edge_curves.cpp \
    libigl/include/igl/face_areas.cpp \
    libigl/include/igl/face_occurrences.cpp \
    libigl/include/igl/faces_first.cpp \
    libigl/include/igl/facet_components.cpp \
    libigl/include/igl/false_barycentric_subdivision.cpp \
    libigl/include/igl/fast_winding_number.cpp \
    libigl/include/igl/file_contents_as_string.cpp \
    libigl/include/igl/file_dialog_open.cpp \
    libigl/include/igl/file_dialog_save.cpp \
    libigl/include/igl/file_exists.cpp \
    libigl/include/igl/find_cross_field_singularities.cpp \
    libigl/include/igl/find_zero.cpp \
    libigl/include/igl/find.cpp \
    libigl/include/igl/fit_plane.cpp \
    libigl/include/igl/fit_rotations.cpp \
    libigl/include/igl/flip_avoiding_line_search.cpp \
    libigl/include/igl/flip_edge.cpp \
    libigl/include/igl/flipped_triangles.cpp \
    libigl/include/igl/flood_fill.cpp \
    libigl/include/igl/floor.cpp \
    libigl/include/igl/forward_kinematics.cpp \
    libigl/include/igl/frame_field_deformer.cpp \
    libigl/include/igl/frame_to_cross_field.cpp \
    libigl/include/igl/frustum.cpp \
    libigl/include/igl/gaussian_curvature.cpp \
    libigl/include/igl/get_seconds_hires.cpp \
    libigl/include/igl/get_seconds.cpp \
    libigl/include/igl/grad_intrinsic.cpp \
    libigl/include/igl/grad.cpp \
    libigl/include/igl/grid_search.cpp \
    libigl/include/igl/grid.cpp \
    libigl/include/igl/group_sum_matrix.cpp \
    libigl/include/igl/guess_extension.cpp \
    libigl/include/igl/HalfEdgeIterator.cpp \
    libigl/include/igl/harmonic.cpp \
    libigl/include/igl/harwell_boeing.cpp \
    libigl/include/igl/hausdorff.cpp \
    libigl/include/igl/heat_geodesics.cpp \
    libigl/include/igl/hessian_energy.cpp \
    libigl/include/igl/hessian.cpp \
    libigl/include/igl/histc.cpp \
    libigl/include/igl/hsv_to_rgb.cpp \
    libigl/include/igl/in_element.cpp \
    libigl/include/igl/infinite_cost_stopping_condition.cpp \
    libigl/include/igl/inradius.cpp \
    libigl/include/igl/internal_angles.cpp \
    libigl/include/igl/intersect.cpp \
    libigl/include/igl/intrinsic_delaunay_cotmatrix.cpp \
    libigl/include/igl/intrinsic_delaunay_triangulation.cpp \
    libigl/include/igl/invert_diag.cpp \
    libigl/include/igl/is_border_vertex.cpp \
    libigl/include/igl/is_boundary_edge.cpp \
    libigl/include/igl/is_delaunay.cpp \
    libigl/include/igl/is_dir.cpp \
    libigl/include/igl/is_edge_manifold.cpp \
    libigl/include/igl/is_file.cpp \
    libigl/include/igl/is_intrinsic_delaunay.cpp \
    libigl/include/igl/is_irregular_vertex.cpp \
    libigl/include/igl/is_planar.cpp \
    libigl/include/igl/is_readable.cpp \
    libigl/include/igl/is_sparse.cpp \
    libigl/include/igl/is_stl.cpp \
    libigl/include/igl/is_symmetric.cpp \
    libigl/include/igl/is_vertex_manifold.cpp \
    libigl/include/igl/is_writable.cpp \
    libigl/include/igl/isdiag.cpp \
    libigl/include/igl/ismember.cpp \
    libigl/include/igl/isolines.cpp \
    libigl/include/igl/jet.cpp \
    libigl/include/igl/knn.cpp \
    libigl/include/igl/launch_medit.cpp \
    libigl/include/igl/lbs_matrix.cpp \
    libigl/include/igl/lexicographic_triangulation.cpp \
    libigl/include/igl/limit_faces.cpp \
    libigl/include/igl/line_field_mismatch.cpp \
    libigl/include/igl/line_search.cpp \
    libigl/include/igl/line_segment_in_rectangle.cpp \
    libigl/include/igl/linprog.cpp \
    libigl/include/igl/list_to_matrix.cpp \
    libigl/include/igl/local_basis.cpp \
    libigl/include/igl/look_at.cpp \
    libigl/include/igl/loop.cpp \
    libigl/include/igl/lscm.cpp \
    libigl/include/igl/map_vertices_to_circle.cpp \
    libigl/include/igl/mapping_energy_with_jacobians.cpp \
    libigl/include/igl/marching_tets.cpp \
    libigl/include/igl/massmatrix_intrinsic.cpp \
    libigl/include/igl/massmatrix.cpp \
    libigl/include/igl/mat_max.cpp \
    libigl/include/igl/mat_min.cpp \
    libigl/include/igl/mat_to_quat.cpp \
    libigl/include/igl/matlab_format.cpp \
    libigl/include/igl/matrix_to_list.cpp \
    libigl/include/igl/max_faces_stopping_condition.cpp \
    libigl/include/igl/max_size.cpp \
    libigl/include/igl/max.cpp \
    libigl/include/igl/median.cpp \
    libigl/include/igl/min_quad_dense.cpp \
    libigl/include/igl/min_quad_with_fixed.cpp \
    libigl/include/igl/min_size.cpp \
    libigl/include/igl/min.cpp \
    libigl/include/igl/mod.cpp \
    libigl/include/igl/mode.cpp \
    libigl/include/igl/mvc.cpp \
    libigl/include/igl/nchoosek.cpp \
    libigl/include/igl/next_filename.cpp \
    libigl/include/igl/normal_derivative.cpp \
    libigl/include/igl/normalize_quat.cpp \
    libigl/include/igl/normalize_row_lengths.cpp \
    libigl/include/igl/normalize_row_sums.cpp \
    libigl/include/igl/null.cpp \
    libigl/include/igl/octree.cpp \
    libigl/include/igl/on_boundary.cpp \
    libigl/include/igl/orient_outward.cpp \
    libigl/include/igl/orientable_patches.cpp \
    libigl/include/igl/oriented_facets.cpp \
    libigl/include/igl/orth.cpp \
    libigl/include/igl/ortho.cpp \
    libigl/include/igl/outer_element.cpp \
    libigl/include/igl/parallel_transport_angles.cpp \
    libigl/include/igl/partition.cpp \
    libigl/include/igl/parula.cpp \
    libigl/include/igl/path_to_executable.cpp \
    libigl/include/igl/pathinfo.cpp \
    libigl/include/igl/per_corner_normals.cpp \
    libigl/include/igl/per_edge_normals.cpp \
    libigl/include/igl/per_face_normals.cpp \
    libigl/include/igl/per_vertex_attribute_smoothing.cpp \
    libigl/include/igl/per_vertex_normals.cpp \
    libigl/include/igl/per_vertex_point_to_plane_quadrics.cpp \
    libigl/include/igl/piecewise_constant_winding_number.cpp \
    libigl/include/igl/pinv.cpp \
    libigl/include/igl/planarize_quad_mesh.cpp \
    libigl/include/igl/point_in_circle.cpp \
    libigl/include/igl/point_in_poly.cpp \
    libigl/include/igl/point_mesh_squared_distance.cpp \
    libigl/include/igl/point_simplex_squared_distance.cpp \
    libigl/include/igl/polar_dec.cpp \
    libigl/include/igl/polar_svd.cpp \
    libigl/include/igl/polar_svd3x3.cpp \
    libigl/include/igl/polygon_mesh_to_triangle_mesh.cpp \
    libigl/include/igl/principal_curvature.cpp \
    libigl/include/igl/print_ijv.cpp \
    libigl/include/igl/print_vector.cpp \
    libigl/include/igl/procrustes.cpp \
    libigl/include/igl/project_isometrically_to_plane.cpp \
    libigl/include/igl/project_to_line_segment.cpp \
    libigl/include/igl/project_to_line.cpp \
    libigl/include/igl/project.cpp \
    libigl/include/igl/pseudonormal_test.cpp \
    libigl/include/igl/pso.cpp \
    libigl/include/igl/qslim_optimal_collapse_edge_callbacks.cpp \
    libigl/include/igl/qslim.cpp \
    libigl/include/igl/quad_planarity.cpp \
    libigl/include/igl/quadric_binary_plus_operator.cpp \
    libigl/include/igl/quat_conjugate.cpp \
    libigl/include/igl/quat_mult.cpp \
    libigl/include/igl/quat_to_axis_angle.cpp \
    libigl/include/igl/quat_to_mat.cpp \
    libigl/include/igl/quats_to_column.cpp \
    libigl/include/igl/ramer_douglas_peucker.cpp \
    libigl/include/igl/random_dir.cpp \
    libigl/include/igl/random_points_on_mesh.cpp \
    libigl/include/igl/random_quaternion.cpp \
    libigl/include/igl/random_search.cpp \
    libigl/include/igl/randperm.cpp \
    libigl/include/igl/ray_box_intersect.cpp \
    libigl/include/igl/ray_mesh_intersect.cpp \
    libigl/include/igl/ray_sphere_intersect.cpp \
    libigl/include/igl/read_triangle_mesh.cpp \
    libigl/include/igl/readBF.cpp \
    libigl/include/igl/readCSV.cpp \
    libigl/include/igl/readDMAT.cpp \
    libigl/include/igl/readMESH.cpp \
    libigl/include/igl/readMSH.cpp \
    libigl/include/igl/readNODE.cpp \
    libigl/include/igl/readOBJ.cpp \
    libigl/include/igl/readOFF.cpp \
    libigl/include/igl/readPLY.cpp \
    libigl/include/igl/readSTL.cpp \
    libigl/include/igl/readTGF.cpp \
    libigl/include/igl/readWRL.cpp \
    libigl/include/igl/remesh_along_isoline.cpp \
    libigl/include/igl/remove_duplicate_vertices.cpp \
    libigl/include/igl/remove_duplicates.cpp \
    libigl/include/igl/remove_unreferenced.cpp \
    libigl/include/igl/reorder.cpp \
    libigl/include/igl/repdiag.cpp \
    libigl/include/igl/repmat.cpp \
    libigl/include/igl/resolve_duplicated_faces.cpp \
    libigl/include/igl/rgb_to_hsv.cpp \
    libigl/include/igl/rotate_by_quat.cpp \
    libigl/include/igl/rotate_vectors.cpp \
    libigl/include/igl/rotation_matrix_from_directions.cpp \
    libigl/include/igl/round.cpp \
    libigl/include/igl/rows_to_matrix.cpp \
    libigl/include/igl/sample_edges.cpp \
    libigl/include/igl/scaf.cpp \
    libigl/include/igl/seam_edges.cpp \
    libigl/include/igl/segment_segment_intersect.cpp \
    libigl/include/igl/setdiff.cpp \
    libigl/include/igl/setunion.cpp \
    libigl/include/igl/setxor.cpp \
    libigl/include/igl/shape_diameter_function.cpp \
    libigl/include/igl/shapeup.cpp \
    libigl/include/igl/shortest_edge_and_midpoint.cpp \
    libigl/include/igl/signed_angle.cpp \
    libigl/include/igl/signed_distance.cpp \
    libigl/include/igl/simplify_polyhedron.cpp \
    libigl/include/igl/slice_cached.cpp \
    libigl/include/igl/slice_into.cpp \
    libigl/include/igl/slice_mask.cpp \
    libigl/include/igl/slice.cpp \
    libigl/include/igl/slim.cpp \
    libigl/include/igl/snap_points.cpp \
    libigl/include/igl/snap_to_canonical_view_quat.cpp \
    libigl/include/igl/snap_to_fixed_up.cpp \
    libigl/include/igl/solid_angle.cpp \
    libigl/include/igl/sort_angles.cpp \
    libigl/include/igl/sort_triangles.cpp \
    libigl/include/igl/sort_vectors_ccw.cpp \
    libigl/include/igl/sort.cpp \
    libigl/include/igl/sortrows.cpp \
    libigl/include/igl/sparse_cached.cpp \
    libigl/include/igl/sparse_voxel_grid.cpp \
    libigl/include/igl/sparse.cpp \
    libigl/include/igl/speye.cpp \
    libigl/include/igl/squared_edge_lengths.cpp \
    libigl/include/igl/stdin_to_temp.cpp \
    libigl/include/igl/straighten_seams.cpp \
    libigl/include/igl/sum.cpp \
    libigl/include/igl/svd3x3_avx.cpp \
    libigl/include/igl/svd3x3_sse.cpp \
    libigl/include/igl/svd3x3.cpp \
    libigl/include/igl/swept_volume_bounding_box.cpp \
    libigl/include/igl/swept_volume_signed_distance.cpp \
    libigl/include/igl/tan_half_angle.cpp \
    libigl/include/igl/tet_tet_adjacency.cpp \
    libigl/include/igl/topological_hole_fill.cpp \
    libigl/include/igl/trackball.cpp \
    libigl/include/igl/transpose_blocks.cpp \
    libigl/include/igl/triangle_fan.cpp \
    libigl/include/igl/triangle_triangle_adjacency.cpp \
    libigl/include/igl/triangles_from_strip.cpp \
    libigl/include/igl/triangulated_grid.cpp \
    libigl/include/igl/two_axis_valuator_fixed_up.cpp \
    libigl/include/igl/uniformly_sample_two_manifold.cpp \
    libigl/include/igl/unique_edge_map.cpp \
    libigl/include/igl/unique_rows.cpp \
    libigl/include/igl/unique_simplices.cpp \
    libigl/include/igl/unique.cpp \
    libigl/include/igl/unproject_in_mesh.cpp \
    libigl/include/igl/unproject_onto_mesh.cpp \
    libigl/include/igl/unproject_ray.cpp \
    libigl/include/igl/unproject.cpp \
    libigl/include/igl/unzip_corners.cpp \
    libigl/include/igl/upsample.cpp \
    libigl/include/igl/vector_area_matrix.cpp \
    libigl/include/igl/vertex_components.cpp \
    libigl/include/igl/vertex_triangle_adjacency.cpp \
    libigl/include/igl/volume.cpp \
    libigl/include/igl/voxel_grid.cpp \
    libigl/include/igl/winding_number.cpp \
    libigl/include/igl/write_triangle_mesh.cpp \
    libigl/include/igl/writeBF.cpp \
    libigl/include/igl/writeDMAT.cpp \
    libigl/include/igl/writeMESH.cpp \
    libigl/include/igl/writeOBJ.cpp \
    libigl/include/igl/writeOFF.cpp \
    libigl/include/igl/writePLY.cpp \
    libigl/include/igl/writeSTL.cpp \
    libigl/include/igl/writeTGF.cpp \
    libigl/include/igl/writeWRL.cpp \
    libigl/include/igl/raytri.c \
    poisson.cpp \
    poissonhelper.cpp

HEADERS += \
    util/tiny_obj_loader.h \
    Eigen/Cholesky \
    Eigen/CholmodSupport \
    Eigen/Core \
    Eigen/Dense \
    Eigen/Eigen \
    Eigen/Eigenvalues \
    Eigen/Geometry \
    Eigen/Householder \
    Eigen/IterativeLinearSolvers \
    Eigen/Jacobi \
    Eigen/LU \
    Eigen/MetisSupport \
    Eigen/OrderingMethods \
    Eigen/PardisoSupport \
    Eigen/PaStiXSupport \
    Eigen/QR \
    Eigen/QtAlignedMalloc \
    Eigen/Sparse \
    Eigen/SparseCholesky \
    Eigen/SparseCore \
    Eigen/SparseLU \
    Eigen/SparseQR \
    Eigen/SPQRSupport \
    Eigen/StdDeque \
    Eigen/StdList \
    Eigen/StdVector \
    Eigen/SuperLUSupport \
    Eigen/SVD \
    Eigen/UmfPackSupport \
    Eigen/src/Cholesky/LDLT.h \
    Eigen/src/Cholesky/LLT.h \
    Eigen/src/Cholesky/LLT_LAPACKE.h \
    Eigen/src/CholmodSupport/CholmodSupport.h \
    Eigen/src/Core/arch/AltiVec/Complex.h \
    Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    Eigen/src/Core/arch/AltiVec/PacketMath.h \
    Eigen/src/Core/arch/AVX/Complex.h \
    Eigen/src/Core/arch/AVX/MathFunctions.h \
    Eigen/src/Core/arch/AVX/PacketMath.h \
    Eigen/src/Core/arch/AVX/TypeCasting.h \
    Eigen/src/Core/arch/AVX512/MathFunctions.h \
    Eigen/src/Core/arch/AVX512/PacketMath.h \
    Eigen/src/Core/arch/CUDA/Complex.h \
    Eigen/src/Core/arch/CUDA/Half.h \
    Eigen/src/Core/arch/CUDA/MathFunctions.h \
    Eigen/src/Core/arch/CUDA/PacketMath.h \
    Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    Eigen/src/Core/arch/CUDA/TypeCasting.h \
    Eigen/src/Core/arch/Default/Settings.h \
    Eigen/src/Core/arch/NEON/Complex.h \
    Eigen/src/Core/arch/NEON/MathFunctions.h \
    Eigen/src/Core/arch/NEON/PacketMath.h \
    Eigen/src/Core/arch/SSE/Complex.h \
    Eigen/src/Core/arch/SSE/MathFunctions.h \
    Eigen/src/Core/arch/SSE/PacketMath.h \
    Eigen/src/Core/arch/SSE/TypeCasting.h \
    Eigen/src/Core/arch/ZVector/Complex.h \
    Eigen/src/Core/arch/ZVector/MathFunctions.h \
    Eigen/src/Core/arch/ZVector/PacketMath.h \
    Eigen/src/Core/functors/AssignmentFunctors.h \
    Eigen/src/Core/functors/BinaryFunctors.h \
    Eigen/src/Core/functors/NullaryFunctors.h \
    Eigen/src/Core/functors/StlFunctors.h \
    Eigen/src/Core/functors/TernaryFunctors.h \
    Eigen/src/Core/functors/UnaryFunctors.h \
    Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    Eigen/src/Core/products/GeneralMatrixMatrix.h \
    Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    Eigen/src/Core/products/GeneralMatrixVector.h \
    Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    Eigen/src/Core/products/Parallelizer.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/SelfadjointMatrixVector.h \
    Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    Eigen/src/Core/products/SelfadjointProduct.h \
    Eigen/src/Core/products/SelfadjointRank2Update.h \
    Eigen/src/Core/products/TriangularMatrixMatrix.h \
    Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularMatrixVector.h \
    Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    Eigen/src/Core/products/TriangularSolverMatrix.h \
    Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    Eigen/src/Core/products/TriangularSolverVector.h \
    Eigen/src/Core/util/BlasUtil.h \
    Eigen/src/Core/util/Constants.h \
    Eigen/src/Core/util/DisableStupidWarnings.h \
    Eigen/src/Core/util/ForwardDeclarations.h \
    Eigen/src/Core/util/Macros.h \
    Eigen/src/Core/util/Memory.h \
    Eigen/src/Core/util/Meta.h \
    Eigen/src/Core/util/MKL_support.h \
    Eigen/src/Core/util/NonMPL2.h \
    Eigen/src/Core/util/ReenableStupidWarnings.h \
    Eigen/src/Core/util/StaticAssert.h \
    Eigen/src/Core/util/XprHelper.h \
    Eigen/src/Core/Array.h \
    Eigen/src/Core/ArrayBase.h \
    Eigen/src/Core/ArrayWrapper.h \
    Eigen/src/Core/Assign.h \
    Eigen/src/Core/Assign_MKL.h \
    Eigen/src/Core/AssignEvaluator.h \
    Eigen/src/Core/BandMatrix.h \
    Eigen/src/Core/Block.h \
    Eigen/src/Core/BooleanRedux.h \
    Eigen/src/Core/CommaInitializer.h \
    Eigen/src/Core/ConditionEstimator.h \
    Eigen/src/Core/CoreEvaluators.h \
    Eigen/src/Core/CoreIterators.h \
    Eigen/src/Core/CwiseBinaryOp.h \
    Eigen/src/Core/CwiseNullaryOp.h \
    Eigen/src/Core/CwiseTernaryOp.h \
    Eigen/src/Core/CwiseUnaryOp.h \
    Eigen/src/Core/CwiseUnaryView.h \
    Eigen/src/Core/DenseBase.h \
    Eigen/src/Core/DenseCoeffsBase.h \
    Eigen/src/Core/DenseStorage.h \
    Eigen/src/Core/Diagonal.h \
    Eigen/src/Core/DiagonalMatrix.h \
    Eigen/src/Core/DiagonalProduct.h \
    Eigen/src/Core/Dot.h \
    Eigen/src/Core/EigenBase.h \
    Eigen/src/Core/ForceAlignedAccess.h \
    Eigen/src/Core/Fuzzy.h \
    Eigen/src/Core/GeneralProduct.h \
    Eigen/src/Core/GenericPacketMath.h \
    Eigen/src/Core/GlobalFunctions.h \
    Eigen/src/Core/Inverse.h \
    Eigen/src/Core/IO.h \
    Eigen/src/Core/Map.h \
    Eigen/src/Core/MapBase.h \
    Eigen/src/Core/MathFunctions.h \
    Eigen/src/Core/MathFunctionsImpl.h \
    Eigen/src/Core/Matrix.h \
    Eigen/src/Core/MatrixBase.h \
    Eigen/src/Core/NestByValue.h \
    Eigen/src/Core/NoAlias.h \
    Eigen/src/Core/NumTraits.h \
    Eigen/src/Core/PermutationMatrix.h \
    Eigen/src/Core/PlainObjectBase.h \
    Eigen/src/Core/Product.h \
    Eigen/src/Core/ProductEvaluators.h \
    Eigen/src/Core/Random.h \
    Eigen/src/Core/Redux.h \
    Eigen/src/Core/Ref.h \
    Eigen/src/Core/Replicate.h \
    Eigen/src/Core/ReturnByValue.h \
    Eigen/src/Core/Reverse.h \
    Eigen/src/Core/Select.h \
    Eigen/src/Core/SelfAdjointView.h \
    Eigen/src/Core/SelfCwiseBinaryOp.h \
    Eigen/src/Core/Solve.h \
    Eigen/src/Core/SolverBase.h \
    Eigen/src/Core/SolveTriangular.h \
    Eigen/src/Core/StableNorm.h \
    Eigen/src/Core/Stride.h \
    Eigen/src/Core/Swap.h \
    Eigen/src/Core/Transpose.h \
    Eigen/src/Core/Transpositions.h \
    Eigen/src/Core/TriangularMatrix.h \
    Eigen/src/Core/VectorBlock.h \
    Eigen/src/Core/VectorwiseOp.h \
    Eigen/src/Core/Visitor.h \
    Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    Eigen/src/Eigenvalues/ComplexSchur.h \
    Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/EigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    Eigen/src/Eigenvalues/RealQZ.h \
    Eigen/src/Eigenvalues/RealSchur.h \
    Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    Eigen/src/Eigenvalues/Tridiagonalization.h \
    Eigen/src/Geometry/arch/Geometry_SSE.h \
    Eigen/src/Geometry/AlignedBox.h \
    Eigen/src/Geometry/AngleAxis.h \
    Eigen/src/Geometry/EulerAngles.h \
    Eigen/src/Geometry/Homogeneous.h \
    Eigen/src/Geometry/Hyperplane.h \
    Eigen/src/Geometry/OrthoMethods.h \
    Eigen/src/Geometry/ParametrizedLine.h \
    Eigen/src/Geometry/Quaternion.h \
    Eigen/src/Geometry/Rotation2D.h \
    Eigen/src/Geometry/RotationBase.h \
    Eigen/src/Geometry/Scaling.h \
    Eigen/src/Geometry/Transform.h \
    Eigen/src/Geometry/Translation.h \
    Eigen/src/Geometry/Umeyama.h \
    Eigen/src/Householder/BlockHouseholder.h \
    Eigen/src/Householder/Householder.h \
    Eigen/src/Householder/HouseholderSequence.h \
    Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    Eigen/src/Jacobi/Jacobi.h \
    Eigen/src/LU/arch/Inverse_SSE.h \
    Eigen/src/LU/Determinant.h \
    Eigen/src/LU/FullPivLU.h \
    Eigen/src/LU/InverseImpl.h \
    Eigen/src/LU/PartialPivLU.h \
    Eigen/src/LU/PartialPivLU_LAPACKE.h \
    Eigen/src/MetisSupport/MetisSupport.h \
    Eigen/src/misc/blas.h \
    Eigen/src/misc/Image.h \
    Eigen/src/misc/Kernel.h \
    Eigen/src/misc/lapack.h \
    Eigen/src/misc/lapacke.h \
    Eigen/src/misc/lapacke_mangling.h \
    Eigen/src/misc/RealSvd2x2.h \
    Eigen/src/OrderingMethods/Amd.h \
    Eigen/src/OrderingMethods/Eigen_Colamd.h \
    Eigen/src/OrderingMethods/Ordering.h \
    Eigen/src/PardisoSupport/PardisoSupport.h \
    Eigen/src/PaStiXSupport/PaStiXSupport.h \
    Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    Eigen/src/plugins/BlockMethods.h \
    Eigen/src/plugins/CommonCwiseBinaryOps.h \
    Eigen/src/plugins/CommonCwiseUnaryOps.h \
    Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    Eigen/src/QR/ColPivHouseholderQR.h \
    Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    Eigen/src/QR/FullPivHouseholderQR.h \
    Eigen/src/QR/HouseholderQR.h \
    Eigen/src/QR/HouseholderQR_LAPACKE.h \
    Eigen/src/SparseCholesky/SimplicialCholesky.h \
    Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    Eigen/src/SparseCore/AmbiVector.h \
    Eigen/src/SparseCore/CompressedStorage.h \
    Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    Eigen/src/SparseCore/MappedSparseMatrix.h \
    Eigen/src/SparseCore/SparseAssign.h \
    Eigen/src/SparseCore/SparseBlock.h \
    Eigen/src/SparseCore/SparseColEtree.h \
    Eigen/src/SparseCore/SparseCompressedBase.h \
    Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    Eigen/src/SparseCore/SparseDenseProduct.h \
    Eigen/src/SparseCore/SparseDiagonalProduct.h \
    Eigen/src/SparseCore/SparseDot.h \
    Eigen/src/SparseCore/SparseFuzzy.h \
    Eigen/src/SparseCore/SparseMap.h \
    Eigen/src/SparseCore/SparseMatrix.h \
    Eigen/src/SparseCore/SparseMatrixBase.h \
    Eigen/src/SparseCore/SparsePermutation.h \
    Eigen/src/SparseCore/SparseProduct.h \
    Eigen/src/SparseCore/SparseRedux.h \
    Eigen/src/SparseCore/SparseRef.h \
    Eigen/src/SparseCore/SparseSelfAdjointView.h \
    Eigen/src/SparseCore/SparseSolverBase.h \
    Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    Eigen/src/SparseCore/SparseTranspose.h \
    Eigen/src/SparseCore/SparseTriangularView.h \
    Eigen/src/SparseCore/SparseUtil.h \
    Eigen/src/SparseCore/SparseVector.h \
    Eigen/src/SparseCore/SparseView.h \
    Eigen/src/SparseCore/TriangularSolver.h \
    Eigen/src/SparseLU/SparseLU.h \
    Eigen/src/SparseLU/SparseLU_column_bmod.h \
    Eigen/src/SparseLU/SparseLU_column_dfs.h \
    Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    Eigen/src/SparseLU/SparseLU_Memory.h \
    Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    Eigen/src/SparseLU/SparseLU_pivotL.h \
    Eigen/src/SparseLU/SparseLU_pruneL.h \
    Eigen/src/SparseLU/SparseLU_relax_snode.h \
    Eigen/src/SparseLU/SparseLU_Structs.h \
    Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    Eigen/src/SparseLU/SparseLU_Utils.h \
    Eigen/src/SparseLU/SparseLUImpl.h \
    Eigen/src/SparseQR/SparseQR.h \
    Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    Eigen/src/StlSupport/details.h \
    Eigen/src/StlSupport/StdDeque.h \
    Eigen/src/StlSupport/StdList.h \
    Eigen/src/StlSupport/StdVector.h \
    Eigen/src/SuperLUSupport/SuperLUSupport.h \
    Eigen/src/SVD/BDCSVD.h \
    Eigen/src/SVD/JacobiSVD.h \
    Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    Eigen/src/SVD/SVDBase.h \
    Eigen/src/SVD/UpperBidiagonalization.h \
    Eigen/src/UmfPackSupport/UmfPackSupport.h \
    libigl/include/igl/copyleft/marching_cubes.h \
    libigl/include/igl/copyleft/marching_cubes_tables.h \
    libigl/include/igl/AABB.h \
    libigl/include/igl/accumarray.h \
    libigl/include/igl/active_set.h \
    libigl/include/igl/adjacency_list.h \
    libigl/include/igl/adjacency_matrix.h \
    libigl/include/igl/all_edges.h \
    libigl/include/igl/all_pairs_distances.h \
    libigl/include/igl/all.h \
    libigl/include/igl/ambient_occlusion.h \
    libigl/include/igl/angular_distance.h \
    libigl/include/igl/any_of.h \
    libigl/include/igl/any.h \
    libigl/include/igl/arap_dof.h \
    libigl/include/igl/arap_linear_block.h \
    libigl/include/igl/arap_rhs.h \
    libigl/include/igl/arap.h \
    libigl/include/igl/ARAPEnergyType.h \
    libigl/include/igl/AtA_cached.h \
    libigl/include/igl/average_onto_faces.h \
    libigl/include/igl/average_onto_vertices.h \
    libigl/include/igl/avg_edge_length.h \
    libigl/include/igl/axis_angle_to_quat.h \
    libigl/include/igl/barycenter.h \
    libigl/include/igl/barycentric_coordinates.h \
    libigl/include/igl/barycentric_to_global.h \
    libigl/include/igl/basename.h \
    libigl/include/igl/bbw.h \
    libigl/include/igl/bfs_orient.h \
    libigl/include/igl/bfs.h \
    libigl/include/igl/biharmonic_coordinates.h \
    libigl/include/igl/bijective_composite_harmonic_mapping.h \
    libigl/include/igl/bone_parents.h \
    libigl/include/igl/boundary_conditions.h \
    libigl/include/igl/boundary_facets.h \
    libigl/include/igl/boundary_loop.h \
    libigl/include/igl/bounding_box_diagonal.h \
    libigl/include/igl/bounding_box.h \
    libigl/include/igl/C_STR.h \
    libigl/include/igl/Camera.h \
    libigl/include/igl/canonical_quaternions.h \
    libigl/include/igl/cat.h \
    libigl/include/igl/ceil.h \
    libigl/include/igl/centroid.h \
    libigl/include/igl/circulation.h \
    libigl/include/igl/circumradius.h \
    libigl/include/igl/collapse_edge.h \
    libigl/include/igl/collapse_small_triangles.h \
    libigl/include/igl/colon.h \
    libigl/include/igl/colormap.h \
    libigl/include/igl/column_to_quats.h \
    libigl/include/igl/columnize.h \
    libigl/include/igl/comb_cross_field.h \
    libigl/include/igl/comb_frame_field.h \
    libigl/include/igl/comb_line_field.h \
    libigl/include/igl/combine.h \
    libigl/include/igl/compute_frame_field_bisectors.h \
    libigl/include/igl/connect_boundary_to_infinity.h \
    libigl/include/igl/cotmatrix_entries.h \
    libigl/include/igl/cotmatrix_intrinsic.h \
    libigl/include/igl/cotmatrix.h \
    libigl/include/igl/count.h \
    libigl/include/igl/covariance_scatter_matrix.h \
    libigl/include/igl/cross_field_mismatch.h \
    libigl/include/igl/cross.h \
    libigl/include/igl/crouzeix_raviart_cotmatrix.h \
    libigl/include/igl/crouzeix_raviart_massmatrix.h \
    libigl/include/igl/cumprod.h \
    libigl/include/igl/cumsum.h \
    libigl/include/igl/cut_mesh_from_singularities.h \
    libigl/include/igl/cut_mesh.h \
    libigl/include/igl/cut_to_disk.h \
    libigl/include/igl/cylinder.h \
    libigl/include/igl/dated_copy.h \
    libigl/include/igl/decimate.h \
    libigl/include/igl/deform_skeleton.h \
    libigl/include/igl/delaunay_triangulation.h \
    libigl/include/igl/deprecated.h \
    libigl/include/igl/dfs.h \
    libigl/include/igl/diag.h \
    libigl/include/igl/dihedral_angles.h \
    libigl/include/igl/dijkstra.h \
    libigl/include/igl/directed_edge_orientations.h \
    libigl/include/igl/directed_edge_parents.h \
    libigl/include/igl/dirname.h \
    libigl/include/igl/dot_row.h \
    libigl/include/igl/dot.h \
    libigl/include/igl/doublearea.h \
    libigl/include/igl/dqs.h \
    libigl/include/igl/ears.h \
    libigl/include/igl/edge_collapse_is_valid.h \
    libigl/include/igl/edge_exists_near.h \
    libigl/include/igl/edge_flaps.h \
    libigl/include/igl/edge_lengths.h \
    libigl/include/igl/edge_topology.h \
    libigl/include/igl/edges_to_path.h \
    libigl/include/igl/edges.h \
    libigl/include/igl/eigs.h \
    libigl/include/igl/EPS.h \
    libigl/include/igl/euler_characteristic.h \
    libigl/include/igl/exact_geodesic.h \
    libigl/include/igl/example_fun.h \
    libigl/include/igl/exterior_edges.h \
    libigl/include/igl/extract_manifold_patches.h \
    libigl/include/igl/extract_non_manifold_edge_curves.h \
    libigl/include/igl/face_areas.h \
    libigl/include/igl/face_occurrences.h \
    libigl/include/igl/faces_first.h \
    libigl/include/igl/facet_components.h \
    libigl/include/igl/false_barycentric_subdivision.h \
    libigl/include/igl/fast_winding_number.h \
    libigl/include/igl/file_contents_as_string.h \
    libigl/include/igl/file_dialog_open.h \
    libigl/include/igl/file_dialog_save.h \
    libigl/include/igl/file_exists.h \
    libigl/include/igl/find_cross_field_singularities.h \
    libigl/include/igl/find_zero.h \
    libigl/include/igl/find.h \
    libigl/include/igl/fit_plane.h \
    libigl/include/igl/fit_rotations.h \
    libigl/include/igl/flip_avoiding_line_search.h \
    libigl/include/igl/flip_edge.h \
    libigl/include/igl/flipped_triangles.h \
    libigl/include/igl/flood_fill.h \
    libigl/include/igl/floor.h \
    libigl/include/igl/for_each.h \
    libigl/include/igl/forward_kinematics.h \
    libigl/include/igl/frame_field_deformer.h \
    libigl/include/igl/frame_to_cross_field.h \
    libigl/include/igl/frustum.h \
    libigl/include/igl/gaussian_curvature.h \
    libigl/include/igl/get_seconds_hires.h \
    libigl/include/igl/get_seconds.h \
    libigl/include/igl/grad_intrinsic.h \
    libigl/include/igl/grad.h \
    libigl/include/igl/grid_search.h \
    libigl/include/igl/grid.h \
    libigl/include/igl/group_sum_matrix.h \
    libigl/include/igl/guess_extension.h \
    libigl/include/igl/HalfEdgeIterator.h \
    libigl/include/igl/harmonic.h \
    libigl/include/igl/harwell_boeing.h \
    libigl/include/igl/hausdorff.h \
    libigl/include/igl/heat_geodesics.h \
    libigl/include/igl/hessian_energy.h \
    libigl/include/igl/hessian.h \
    libigl/include/igl/histc.h \
    libigl/include/igl/Hit.h \
    libigl/include/igl/hsv_to_rgb.h \
    libigl/include/igl/igl_inline.h \
    libigl/include/igl/in_element.h \
    libigl/include/igl/IndexComparison.h \
    libigl/include/igl/infinite_cost_stopping_condition.h \
    libigl/include/igl/inradius.h \
    libigl/include/igl/internal_angles.h \
    libigl/include/igl/intersect.h \
    libigl/include/igl/intrinsic_delaunay_cotmatrix.h \
    libigl/include/igl/intrinsic_delaunay_triangulation.h \
    libigl/include/igl/invert_diag.h \
    libigl/include/igl/IO \
    libigl/include/igl/is_border_vertex.h \
    libigl/include/igl/is_boundary_edge.h \
    libigl/include/igl/is_delaunay.h \
    libigl/include/igl/is_dir.h \
    libigl/include/igl/is_edge_manifold.h \
    libigl/include/igl/is_file.h \
    libigl/include/igl/is_intrinsic_delaunay.h \
    libigl/include/igl/is_irregular_vertex.h \
    libigl/include/igl/is_planar.h \
    libigl/include/igl/is_readable.h \
    libigl/include/igl/is_sparse.h \
    libigl/include/igl/is_stl.h \
    libigl/include/igl/is_symmetric.h \
    libigl/include/igl/is_vertex_manifold.h \
    libigl/include/igl/is_writable.h \
    libigl/include/igl/isdiag.h \
    libigl/include/igl/ismember.h \
    libigl/include/igl/isolines.h \
    libigl/include/igl/jet.h \
    libigl/include/igl/knn.h \
    libigl/include/igl/launch_medit.h \
    libigl/include/igl/lbs_matrix.h \
    libigl/include/igl/lexicographic_triangulation.h \
    libigl/include/igl/limit_faces.h \
    libigl/include/igl/line_field_mismatch.h \
    libigl/include/igl/line_search.h \
    libigl/include/igl/line_segment_in_rectangle.h \
    libigl/include/igl/linprog.h \
    libigl/include/igl/LinSpaced.h \
    libigl/include/igl/list_to_matrix.h \
    libigl/include/igl/local_basis.h \
    libigl/include/igl/look_at.h \
    libigl/include/igl/loop.h \
    libigl/include/igl/lscm.h \
    libigl/include/igl/map_vertices_to_circle.h \
    libigl/include/igl/mapping_energy_with_jacobians.h \
    libigl/include/igl/MappingEnergyType.h \
    libigl/include/igl/marching_tets.h \
    libigl/include/igl/massmatrix_intrinsic.h \
    libigl/include/igl/massmatrix.h \
    libigl/include/igl/mat_max.h \
    libigl/include/igl/mat_min.h \
    libigl/include/igl/mat_to_quat.h \
    libigl/include/igl/material_colors.h \
    libigl/include/igl/matlab_format.h \
    libigl/include/igl/matrix_to_list.h \
    libigl/include/igl/max_faces_stopping_condition.h \
    libigl/include/igl/max_size.h \
    libigl/include/igl/max.h \
    libigl/include/igl/median.h \
    libigl/include/igl/MeshBooleanType.h \
    libigl/include/igl/min_quad_dense.h \
    libigl/include/igl/min_quad_with_fixed.h \
    libigl/include/igl/min_size.h \
    libigl/include/igl/min.h \
    libigl/include/igl/mod.h \
    libigl/include/igl/mode.h \
    libigl/include/igl/mvc.h \
    libigl/include/igl/nchoosek.h \
    libigl/include/igl/next_filename.h \
    libigl/include/igl/normal_derivative.h \
    libigl/include/igl/normalize_quat.h \
    libigl/include/igl/normalize_row_lengths.h \
    libigl/include/igl/normalize_row_sums.h \
    libigl/include/igl/NormalType.h \
    libigl/include/igl/null.h \
    libigl/include/igl/octree.h \
    libigl/include/igl/on_boundary.h \
    libigl/include/igl/ONE.h \
    libigl/include/igl/orient_outward.h \
    libigl/include/igl/orientable_patches.h \
    libigl/include/igl/oriented_facets.h \
    libigl/include/igl/orth.h \
    libigl/include/igl/ortho.h \
    libigl/include/igl/outer_element.h \
    libigl/include/igl/parallel_for.h \
    libigl/include/igl/parallel_transport_angles.h \
    libigl/include/igl/partition.h \
    libigl/include/igl/parula.h \
    libigl/include/igl/path_to_executable.h \
    libigl/include/igl/pathinfo.h \
    libigl/include/igl/per_corner_normals.h \
    libigl/include/igl/per_edge_normals.h \
    libigl/include/igl/per_face_normals.h \
    libigl/include/igl/per_vertex_attribute_smoothing.h \
    libigl/include/igl/per_vertex_normals.h \
    libigl/include/igl/per_vertex_point_to_plane_quadrics.h \
    libigl/include/igl/PI.h \
    libigl/include/igl/piecewise_constant_winding_number.h \
    libigl/include/igl/pinv.h \
    libigl/include/igl/planarize_quad_mesh.h \
    libigl/include/igl/ply.h \
    libigl/include/igl/point_in_circle.h \
    libigl/include/igl/point_in_poly.h \
    libigl/include/igl/point_mesh_squared_distance.h \
    libigl/include/igl/point_simplex_squared_distance.h \
    libigl/include/igl/polar_dec.h \
    libigl/include/igl/polar_svd.h \
    libigl/include/igl/polar_svd3x3.h \
    libigl/include/igl/polygon_mesh_to_triangle_mesh.h \
    libigl/include/igl/principal_curvature.h \
    libigl/include/igl/print_ijv.h \
    libigl/include/igl/print_vector.h \
    libigl/include/igl/procrustes.h \
    libigl/include/igl/project_isometrically_to_plane.h \
    libigl/include/igl/project_to_line_segment.h \
    libigl/include/igl/project_to_line.h \
    libigl/include/igl/project.h \
    libigl/include/igl/pseudonormal_test.h \
    libigl/include/igl/pso.h \
    libigl/include/igl/qslim_optimal_collapse_edge_callbacks.h \
    libigl/include/igl/qslim.h \
    libigl/include/igl/quad_planarity.h \
    libigl/include/igl/quadric_binary_plus_operator.h \
    libigl/include/igl/quat_conjugate.h \
    libigl/include/igl/quat_mult.h \
    libigl/include/igl/quat_to_axis_angle.h \
    libigl/include/igl/quat_to_mat.h \
    libigl/include/igl/quats_to_column.h \
    libigl/include/igl/ramer_douglas_peucker.h \
    libigl/include/igl/random_dir.h \
    libigl/include/igl/random_points_on_mesh.h \
    libigl/include/igl/random_quaternion.h \
    libigl/include/igl/random_search.h \
    libigl/include/igl/randperm.h \
    libigl/include/igl/ray_box_intersect.h \
    libigl/include/igl/ray_mesh_intersect.h \
    libigl/include/igl/ray_sphere_intersect.h \
    libigl/include/igl/read_triangle_mesh.h \
    libigl/include/igl/readBF.h \
    libigl/include/igl/readCSV.h \
    libigl/include/igl/readDMAT.h \
    libigl/include/igl/readMESH.h \
    libigl/include/igl/readMSH.h \
    libigl/include/igl/readNODE.h \
    libigl/include/igl/readOBJ.h \
    libigl/include/igl/readOFF.h \
    libigl/include/igl/readPLY.h \
    libigl/include/igl/readSTL.h \
    libigl/include/igl/readTGF.h \
    libigl/include/igl/readWRL.h \
    libigl/include/igl/REDRUM.h \
    libigl/include/igl/redux.h \
    libigl/include/igl/remesh_along_isoline.h \
    libigl/include/igl/remove_duplicate_vertices.h \
    libigl/include/igl/remove_duplicates.h \
    libigl/include/igl/remove_unreferenced.h \
    libigl/include/igl/reorder.h \
    libigl/include/igl/repdiag.h \
    libigl/include/igl/repmat.h \
    libigl/include/igl/resolve_duplicated_faces.h \
    libigl/include/igl/rgb_to_hsv.h \
    libigl/include/igl/rotate_by_quat.h \
    libigl/include/igl/rotate_vectors.h \
    libigl/include/igl/rotation_matrix_from_directions.h \
    libigl/include/igl/round.h \
    libigl/include/igl/rows_to_matrix.h \
    libigl/include/igl/sample_edges.h \
    libigl/include/igl/scaf.h \
    libigl/include/igl/seam_edges.h \
    libigl/include/igl/segment_segment_intersect.h \
    libigl/include/igl/serialize.h \
    libigl/include/igl/setdiff.h \
    libigl/include/igl/setunion.h \
    libigl/include/igl/setxor.h \
    libigl/include/igl/shape_diameter_function.h \
    libigl/include/igl/shapeup.h \
    libigl/include/igl/shortest_edge_and_midpoint.h \
    libigl/include/igl/signed_angle.h \
    libigl/include/igl/signed_distance.h \
    libigl/include/igl/simplify_polyhedron.h \
    libigl/include/igl/Singular_Value_Decomposition_Givens_QR_Factorization_Kernel.hpp \
    libigl/include/igl/Singular_Value_Decomposition_Jacobi_Conjugation_Kernel.hpp \
    libigl/include/igl/Singular_Value_Decomposition_Kernel_Declarations.hpp \
    libigl/include/igl/Singular_Value_Decomposition_Main_Kernel_Body.hpp \
    libigl/include/igl/Singular_Value_Decomposition_Preamble.hpp \
    libigl/include/igl/slice_cached.h \
    libigl/include/igl/slice_into.h \
    libigl/include/igl/slice_mask.h \
    libigl/include/igl/slice.h \
    libigl/include/igl/slim.h \
    libigl/include/igl/snap_points.h \
    libigl/include/igl/snap_to_canonical_view_quat.h \
    libigl/include/igl/snap_to_fixed_up.h \
    libigl/include/igl/solid_angle.h \
    libigl/include/igl/SolverStatus.h \
    libigl/include/igl/sort_angles.h \
    libigl/include/igl/sort_triangles.h \
    libigl/include/igl/sort_vectors_ccw.h \
    libigl/include/igl/sort.h \
    libigl/include/igl/SortableRow.h \
    libigl/include/igl/sortrows.h \
    libigl/include/igl/sparse_cached.h \
    libigl/include/igl/sparse_voxel_grid.h \
    libigl/include/igl/sparse.h \
    libigl/include/igl/speye.h \
    libigl/include/igl/squared_edge_lengths.h \
    libigl/include/igl/stdin_to_temp.h \
    libigl/include/igl/STR.h \
    libigl/include/igl/straighten_seams.h \
    libigl/include/igl/sum.h \
    libigl/include/igl/svd3x3_avx.h \
    libigl/include/igl/svd3x3_sse.h \
    libigl/include/igl/svd3x3.h \
    libigl/include/igl/swept_volume_bounding_box.h \
    libigl/include/igl/swept_volume_signed_distance.h \
    libigl/include/igl/tan_half_angle.h \
    libigl/include/igl/tet_tet_adjacency.h \
    libigl/include/igl/Timer.h \
    libigl/include/igl/topological_hole_fill.h \
    libigl/include/igl/trackball.h \
    libigl/include/igl/transpose_blocks.h \
    libigl/include/igl/triangle_fan.h \
    libigl/include/igl/triangle_triangle_adjacency.h \
    libigl/include/igl/triangles_from_strip.h \
    libigl/include/igl/triangulated_grid.h \
    libigl/include/igl/two_axis_valuator_fixed_up.h \
    libigl/include/igl/uniformly_sample_two_manifold.h \
    libigl/include/igl/unique_edge_map.h \
    libigl/include/igl/unique_rows.h \
    libigl/include/igl/unique_simplices.h \
    libigl/include/igl/unique.h \
    libigl/include/igl/unproject_in_mesh.h \
    libigl/include/igl/unproject_onto_mesh.h \
    libigl/include/igl/unproject_ray.h \
    libigl/include/igl/unproject.h \
    libigl/include/igl/unzip_corners.h \
    libigl/include/igl/upsample.h \
    libigl/include/igl/vector_area_matrix.h \
    libigl/include/igl/verbose.h \
    libigl/include/igl/vertex_components.h \
    libigl/include/igl/vertex_triangle_adjacency.h \
    libigl/include/igl/Viewport.h \
    libigl/include/igl/volume.h \
    libigl/include/igl/voxel_grid.h \
    libigl/include/igl/winding_number.h \
    libigl/include/igl/WindingNumberAABB.h \
    libigl/include/igl/WindingNumberMethod.h \
    libigl/include/igl/WindingNumberTree.h \
    libigl/include/igl/write_triangle_mesh.h \
    libigl/include/igl/writeBF.h \
    libigl/include/igl/writeDMAT.h \
    libigl/include/igl/writeMESH.h \
    libigl/include/igl/writeOBJ.h \
    libigl/include/igl/writeOFF.h \
    libigl/include/igl/writePLY.h \
    libigl/include/igl/writeSTL.h \
    libigl/include/igl/writeTGF.h \
    libigl/include/igl/writeWRL.h \
    libigl/include/igl/ZERO.h \
    poisson.h \
    poissonhelper.h
